### PR TITLE
Request Hint Method Added.

### PR DESCRIPTION
**Pull request by ishtiyak-ahmad**
As a part of sms retreiver api requestHint method missing in this package.

### CODE REVIEW

**Comment by faizalshap** [comment]
Hi @ishtiyak-ahmad  can you please clarify what this method does ?

**Comment by ishtiyak-ahmad** [comment]
this method is part of sms retreiver api and its show available phone number list.
see hint selector in this image. url given in below-
[](https://developers.google.com/identity/sms-retriever/flow-overview.png)

**Comment by faizalshap** [comment]
I will check this, thanks

**Comment by faizalshap** [comment]
@ishtiyak-ahmad  please resolve conflicts

**Comment by ishtiyak-ahmad** [comment]
conflicts resolved.

**Comment by rishabhshakyamm** [comment]
@faizalshap any updates on this PR ? will this be merged?

**Comment by rnkdsh** [comment]
Any updates when it will be merged?

**Comment by faizalshap** [comment]
Hi @ishtiyak-ahmad  @rnkdsh  @rishabhshakyamm 
sorry for being super late due to my work.
I have updated the code and added Hint using new APIs as the ones in this pull request were deprecated.
Thanks

**Pull request closed without merging**
