### PR TITLE
Add support for Android 14

### PR DESCRIPTION
**Pull request by jerearaujo03**
This PR adds 5th param "flags" for method `registerReceiver`, required for Android 14.

### CODE REVIEW

**Comment by jerearaujo03** [comment]
Fix issue #105

**Comment by jerearaujo03** [comment]
TODO: fix for older react native versions

https://github.com/faizalshap/react-native-otp-verify/issues/105#issuecomment-1919139680

**Review by pgim03 — APPROVED** [review]

**Review by fabiansanab — APPROVED** [review]

**Comment by jerearaujo03** [comment]
@faizalshap can you take a look?

**Review by pushpender-singh-ap — APPROVED** [review]

**Review by Titozzz — APPROVED** [review]

**Comment by jerearaujo03** [comment]
Any updates @faizalshap ?

**Review by faizalshap — APPROVED** [review]

**Comment by faizalshap** [comment]
Merged and Published in v1.1.8x

**Comment by Inayat567** [comment]
@faizalshap still crashing on android 14 when otp received

otp receives , fetch otp, fill otp input 

then app crashing

environment

 "react-native": "0.73.6",
   "react-native-otp-verify": "^1.1.8",

**Pull request merged**
