### PR TITLE
added annonation module

### PR DESCRIPTION
**Pull request by Raunak-Agrawal**

### CODE REVIEW

**Comment by faizalshap** [comment]
hi @Raunak-Agrawal 
Thanks for contributing to this repo.
Please add description of what this PR aims to resolve or add.
Regards,

**Comment by Raunak-Agrawal** [comment]
I have changed android to androidx in RNOtpVerifyModule.java file for this line "import android.support.annotation.NonNull". I was using this library in my project and it couldn't resolve because of android. After changing to androidx it got solved. So i raised a PR for the same

**Comment by Raunak-Agrawal** [comment]
Any updates on this @faizalshap ?

**Comment by Raunak-Agrawal** [comment]
Thank you faizal :)
Raunak

**Comment by hosseinmd** [comment]
Could you publish this?

**Pull request merged**
